version: "3.7"

services:
  sunrisa_server:
    depends_on:
      - db
    build: .
    ports:
      - '5000:5000'
    container_name: sunrisa-server-container
    image: sunrisa_server
  db:
    image: mysql:5.7
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      #  nginx:
      #    image: nginx:latest
      #    container_name: production_nginx
      #    volumes:
      #      - ./nginx.conf:/etc/nginx/nginx.conf
      #    ports:
      #      - 80:80
      #      - 443:443


volumes:
  db_data: {}
