version: "3.7"

services:
  sunrisa_server:
    depends_on:
      - db
    build: .
    ports:
      - '5000:5000'
    expose:
      # Opens port 5000 on the container
      - '5000'
    container_name: sunrisa-server-container
    image: sunrisa_server
  db:
    image: mysql:5.7
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      # TODO(sunrisalights): Uncomment when nginx is ported over correctly
      #  nginx:
      #    container_name: nginx
      #    hostname: nginx
      #    image: nginx
      #    ports:
      #      - 80:80
      #      - 443:443
      #    volumes:
      #      - /etc/nginx/sites-enabled/sunrisa:/etc/nginx/sites-enabled/sunrisa
      #      - /etc/letsencrypt:/etc/letsencrypt



volumes:
  db_data: {}
